push_indications:
  name: Push Counter Indication(s)
  description: Send new indication value to Moscow PGU server
  target:
    entity:
      device_class: pgu_indications

  fields:
    indications:
      name: Indication Value(s)
      description: >-
        Indication value(s) for given meter, provided in a form of number
        (for multiple values, a comma-separated list of values, or a list, when called via YAML)
      required: true
      advanced: false
      example: 123
      selector:
        text:
          multiline: false

    service_type:
      name: Indications Service Type
      description: Indications type (for "Flat"-class entities)
      required: false
      advanced: false
      example: Water
      selector:
        select:
          options:
            - Water
            - Electric

    force:
      name: Disable Integrity Checks
      description: >-
        Force indication submission by ignoring several integrity checks.\n
        Does not override `Dry Run` option.
      required: false
      advanced: true
      example: true
      default: false
      selector:
        boolean:

    dry_run:
      name: Dry Run
      description: >-
        Simulate indications submission.
        Values provided as part of 'Indication Value(s)' parameter are not
        registered as new indications. Submission events and entity updates
        remain. Use it to test service calls.
      required: false
      advanced: false
      example: true
      default: false
      selector:
        boolean: